### ISSUE TITLE
ValueError from Jinja PackageLoader

### ISSUE THREAD

**Issue by akimotode** [erdogant/d3graph#14]
When installing d3graph from pip I got the following error when initializing like this `d3 = d3graph.d3graph()`.

_ValueError: The 'd3graph.d3graph' package was not installed in a way that PackageLoader understands._

Error seems to be in line 538 of d3graph.js. I switched that line to the following statement, which solved the problem for me...

jinja_env = Environment(loader=PackageLoader(**'d3graph'**, package_path='d3js'))

Not sure if that is just me, or a general issue

**Comment by erdogant** [comment]
Thanks for mentioning it! I have been playing around and in my case it remains working. Are you maybe using a Jupyter notebook?

**Comment by erdogant** [comment]
I created a new update. Can you try whether this solves your issue?

`pip install -U d3graph`

**Comment by erdogant** [comment]
If you still experience issues, let me know and reopen this issue. For now, I assume it is fixed and I am closing this one.
