### ISSUE TITLE
Hide slider

### ISSUE THREAD

**Issue by nicohlr** [erdogant/d3graph#15]
Hello,

Thanks for the amazing work on this library. I was wondering if it is possible to disable or to hide the "Link Threshold" slider at the top of the graph ? I did not find any parameter to do it in the code.

Thanks for your help.

**Comment by erdogant** [comment]
I added this functionality!

update with:
`pip install -U d3graph`

See [documentation](More information can be found in the [documentation](https://erdogant.github.io/d3graph/pages/html/Examples.html#hide-slider).) for more information.

**Comment by nicohlr** [comment]
Thanks a lot @erdogant !
