### ISSUE TITLE
Is there a way to start the graph at a specific threshold of edges?

### ISSUE THREAD

**Issue by Wario84** [erdogant/d3graph#17]
Hi,

I'm using your package to render some networks, and it works great.
I was wondering if there is a way to set the `d3.show()` to start at a specific value for the threshold of edges?

Thanks a lot,

Mario

**Comment by erdogant** [comment]
At the moment this feature is not yet implemented.

**Comment by davide-aloi** [comment]
I am interested in this feature too. Meantime, wouldn't a similar behaviour be reached by using the minmax argument? My issue is that I am trying to visualise a 90 nodes graph. The edges go from 0 to 68, however, when the graph is initialised and the threshold is 0, the nodes are bouncing all over the place until I set the threshold to say, 3-4. 

I have tried to use the  minmax argument but perhaps I misunderstand its functionality.

`d3.D3graph.set_edge_properties(directed=True, marker_end='arrow', minmax=[5, 68], scaler='zscore', marker_color = '#7295b0')
`
Best,
Davide

**Comment by erdogant** [comment]
I created an update and this functionality is now included! 
* See [documentation pages](https://erdogant.github.io/d3graph/pages/html/Slider%20Properties.html) for more information.

Update to the latest version with
`pip install -U d3graph
`
