### ISSUE TITLE
Is it possible to change the color of the nodes when they get clicked on ? 

### ISSUE THREAD

**Issue by tomascolla95** [erdogant/d3graph#19]
I mean, when I click on a node it's color changes from blue to red, and when I click on another node this new node changes from blue to red while the previous selected node goes back to blue

**Comment by erdogant** [comment]
Yes, this is possible. I implemented the feature.

update to the latest version with:
`pip install -U d3graph
`

```
from d3graph import d3graph
d3 = d3graph()
adjmat, df = d3.import_example('karate')
d3.graph(adjmat, color='cluster')

# specify click event
html = d3.show(click={'fill': 'green', 'stroke': 'black', 'size': 2, 'stroke-width': 2})
# No event
html = d3.show(click=None)
# Default event
html = d3.show()

```

**Comment by erdogant** [comment]
I am closing this one as it is resolved.
