### ISSUE TITLE
d3graph  error

### ISSUE THREAD

**Issue by marvensherif** [erdogant/d3graph#2]
code: 
from d3graph import d3graph, vec2adjmat
source = ['node A','node F','node B','node B','node B','node A','node C','node Z']
target = ['node F','node B','node J','node F','node F','node M','node M','node A']
weight = [5.56, 0.5, 0.64, 0.23, 0.9,3.28,0.5,0.45]

adjmat = vec2adjmat(source, target, weight=weight)
out = d3graph(adjmat)

i got this error:
'charmap' codec can't encode character '\u03b5' in position 44258: character maps to <undefined>

**Comment by erdogant** [comment]
Thank you for reporting. I bug fixed some parts and created an update. Can you check whether it works now?

Update with:

`pip install -U d3graph`

**Comment by marvensherif** [comment]
i tried new update but it give same error

**Comment by erdogant** [comment]
Can you list the used version of python and these:

```
import d3graph
print(d3graph.__version__)
import jinja2
print(jinja2.__version__)


```

**Comment by erdogant** [comment]
Give it another try. I now write to html with utf-8 encoding. 

`pip install -U d3graph
`

**Comment by marvensherif** [comment]
@erdogant It works. Thanks for your help

**Comment by marvensherif** [comment]
Also i have a question is there option for printing the weight between edges on each edge beside to increasing edge size ,and what about self loops can i show it?
