### ISSUE TITLE
Color of the name of the nodes 

### ISSUE THREAD

**Issue by davide-aloi** [erdogant/d3graph#22]
Hello everyone.

Thanks for the amazing library. I am using it to display the Human Connectome in an interactive manner and I really like the result.

However, I was wondering if I could change the color of the names of the nodes? It's the same as the colors of the edges and when you have many nodes - like in my case - it makes it difficult to find the nodes of interest. 

Best,
Davide

**Comment by erdogant** [comment]
Good suggestion. I implemented this and released a new version.
update to: `pip install -U d3graph`

See example over [here](https://erdogant.github.io/d3graph/pages/html/Core_Functionalities.html#node-text-color)

**Comment by erdogant** [comment]
closing this one as it is solved.
