### ISSUE TITLE
Type object is not subscriptable.

### ISSUE THREAD

**Issue by wouteradem** [erdogant/d3graph#26]
Hi,

When trying to use the d3graph library I get the following error:

TypeError: 'type' object is not subscriptable

`878                 minmax: list[float] = [0.5, 15],`
`879                 minmax_distance: list[float] = [50, 100],`

I believe this should be changed to:

`878                 minmax: list = [0.5, 15],`
`879                 minmax_distance: list = [50, 100],`

**Comment by wouteradem** [comment]
Added a PR (in case this is considered a bug): https://github.com/erdogant/d3graph/pull/27

**Comment by erdogant** [comment]
Closing because this issue if fixed.
