### ISSUE TITLE
Remove edges label when they are filtered out by the threshold

### ISSUE THREAD

**Issue by tillwf** [erdogant/d3graph#28]
I have a big graph and when I want to remove small edges I keep having their label floating around. It makes it unreadable.

Here is a screenshot from the doc:
![image](https://github.com/erdogant/d3graph/assets/7115035/7a63687e-16ab-443c-8a21-e02c016bd658)

Is there a way to remove them dynamically?

**Comment by erdogant** [comment]
Good point. So when you break the network with the slider, the labels should also be removed that are associated with the edges. I will check whether this is an easy fix.

**Comment by erdogant** [comment]
I created an update that removes the edge labels. Can you check whether this works too for you?
Update to the latest version with:

`pip install -U d3graph
`
