### ISSUE TITLE
Suggestion : Edge style

### ISSUE THREAD

**Issue by ginkyenglee** [erdogant/d3graph#30]
Thanks for sharing such a great tool to draw graph!

It would be great if we can adjust different line-styles with edge properties such as `dotted('.')`, `dashed('-')`

**Comment by erdogant** [comment]
Good suggestion. I am going to look into it.

**Comment by erdogant** [comment]
I added this functionality. Update to the latest version with:

`pip install -U d3graph`

More information can be found [here](https://erdogant.github.io/d3graph/pages/html/Edge%20properties.html#edge-style)
