### ISSUE TITLE
Directed edges have inconsistent direction

### ISSUE THREAD

**Issue by jonititan** [erdogant/d3graph#5]
It can be seen from your big bang example 
[Big Bang Directed Arrows](https://erdogant.github.io/d3graph/pages/html/Examples.html#directed-arrows)
source = ['Penny', 'Penny', 'Amy', 'Bernadette', 'Bernadette', 'Sheldon', 'Sheldon', 'Sheldon', 'Rajesh']
target = ['Leonard', 'Amy', 'Bernadette', 'Rajesh', 'Howard', 'Howard', 'Leonard', 'Amy', 'Penny']
Some arrows show direction from target to source but they should be from source to target.
In this instance it affects all arrows with Sheldon as source.
Sheldon who only appears in the source list but in the rendered network all the arrows on the edges point towards his node.

The most likely culprit is the js code as I cannot see it in the python portions.
[JS Code](https://github.com/erdogant/d3graph/blob/master/d3graph/d3js/d3graphscript.js)

**Comment by erdogant** [comment]
Nice catch! It should be fixed now! It was because I did not explicitly used `nx.DiGraph()` but the normal `Graph()`.

Update with:

`pip install -U d3graph`
version should be >= 2.0.4

**Comment by jonititan** [comment]
I'll try it out.

Thanks for such a quick response.

Kind regards

Joni

**Comment by jonititan** [comment]
Yes all working now thank you.
