### ISSUE TITLE
Change text size of the node labels

### ISSUE THREAD

**Issue by Akanksha-KronosBio** [erdogant/d3graph#6]
Hi,

Is there a way to check the size and color of the fonts of the node label?

**Comment by erdogant** [comment]
Yes sure. See [here](https://erdogant.github.io/d3graph/pages/html/Core%20Functionalities.html?highlight=edge_properties) some documentation.

All information is stored in `node_properties `and `edge_properties`

```
# Import library
from d3graph import d3graph
# Initialization
d3 = d3graph()
adjmat = d3.import_example('bigbang')
# Process the adjacency matrix
d3.graph(adjmat)
# Show the plot
d3.show()

# The edge properties
print(d3.edge_properties)
# The node properties
print(d3.node_properties)

# Changing the dict will directly make changes in the plot
d3.node_properties['Sheldon']['size']=25
d3.node_properties['Sheldon']['color']='#000000'
d3.show()
```

**Comment by erdogant** [comment]
Re-open this issue and let me know if you had something else in mind.

**Comment by shamangary** [comment]
Hello @erdogant, great library.

I encounter the same issue that's the "label text fontsize" is not tunable.
I believe the `d3.node_properties` can only control node size but not the label itself?

Do you mind to tell me how to change it? Thanks!!

**Comment by erdogant** [comment]
Yes! I implemented functionality for change fontsize! See [here](https://erdogant.github.io/d3graph/pages/html/Core_Functionalities.html#node-fontsize) for an example.

Do not forget to update first to the latest version: `pip install -U d3graph`
