### ISSUE TITLE
Changing Edge Color and Hover on Edge

### ISSUE THREAD

**Issue by SruthiVenkat** [erdogant/d3graph#7]
Hello,

I tried `d3.edge_properties[edge]['color']='#FF0000'` but that does not seem to work.

Also, is hover on edge supported?

**Comment by mzy2240** [comment]
Same here. Changing edge color does not take any effect.

**Comment by erdogant** [comment]
Not sure how this happened but I fixed it and created a new release! Update with:
Version should be>= v2.2.0

`pip install -U d3graph`
