### ISSUE TITLE
Allow Jinja2 Version to move beyond 3

### ISSUE THREAD

**Issue by JohnOmernik** [erdogant/d3graph#9]
Many of the latest Jupyter Notebook Envs require a newer version of Jinja2, but requirements have it locked.  I am going to test without locking, but I thought if it's locked for a reason that we talk it through.

**Comment by JohnOmernik** [comment]
Note, after removing the JINJA2 requirement in both the setup.py and the requirements.txt (shouldn't the setup.py load from the requirements.txt so there are not two places to update?) I installed via python setup.py install and its working with Jinja 3.0.3.  

Perhaps the error that was happening with Later Jinjas was resolved in 3.0.3 and the version checks should allow it to continue to be used. 

Also, interestingly, when the setup.py tries to read the README.md there are some characters that get a Unicode Decode error on Microsoft Windows. Perhaps to be more future proof, we should have the long description just be in the setup.py and not be read from the README.md?

Anywho, sorry for the meandering follow-up.  I guess on JINJA2 issue, where did there error occur that required the version lock, because I don't think we are seeing anymore.

**Comment by erdogant** [comment]
True. It is about time to move beyond the version-locked Jinja version. There was indeed an error that occurred which I could not easily fix but if that is fixed now, lets remove the version lock :-)

I also agree with the setup and requirements file. It is better to have it at one place. 

The windows unicode error is new to me but moving the long description to the setup file is fine too!

**Comment by erdogant** [comment]
I created a new release with this update! Update with:

`pip install -U d3graph`
